[build]
  # pasta que contém seus HTML/CSS/JS
  publish = "public"
  # pasta onde ficam as suas Netlify Functions
  functions = "netlify/functions"

# (Opcional) se você tiver um comando de build, descomente e ajuste:
# [build]
#   command = "npm run build"
#   publish = "dist"
#   functions = "netlify/functions"
